# Generated by Django 4.2.3 on 2023-08-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('faqid', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(blank=True, max_length=100, null=True)),
                ('respuesta', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'faq',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('temaid', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tema',
            },
        ),
    ]
