# Generated by Django 4.2.3 on 2023-08-11 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faq', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='idAdministrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.administrador'),
        ),
        migrations.AddField(
            model_name='tema',
            name='idColaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.colaborador'),
        ),
        migrations.AddField(
            model_name='faq',
            name='idAdministrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.administrador'),
        ),
        migrations.AddField(
            model_name='faq',
            name='idColaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.colaborador'),
        ),
        migrations.AddField(
            model_name='faq',
            name='temaid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.tema'),
        ),
    ]
