# Generated by Django 4.2.3 on 2023-08-14 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('faq', '0003_remove_faq_temaid_delete_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='fecha_creacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='idAdministrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.administrador'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='idColaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.colaborador'),
        ),
    ]
