# Generated by Django 4.2.3 on 2023-08-11 18:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fases',
            fields=[
                ('idFase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('A', 'Activa'), ('I', 'Inactiva')], max_length=1)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('fecha_inactivacion', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fases',
                'verbose_name_plural': 'Fases',
                'db_table': 'Fases',
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('idtimeline', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'timeline',
                'verbose_name_plural': 'timelines',
                'db_table': 'timeline',
            },
        ),
        migrations.CreateModel(
            name='Timeline_fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('A', 'Aprobado'), ('S', 'Suspendido'), ('E', 'Espera'), ('N', 'Negado')], max_length=1)),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases_to_timeline', to='timeline.fases')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_to_fases', to='timeline.timeline')),
            ],
            options={
                'verbose_name': 'Timeline_fase',
                'verbose_name_plural': 'Timeline_fase',
                'db_table': 'Timeline_fase',
            },
        ),
        migrations.AddField(
            model_name='timeline',
            name='fases',
            field=models.ManyToManyField(through='timeline.Timeline_fase', to='timeline.fases'),
        ),
    ]
