# Generated by Django 4.2.6 on 2024-01-28 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Permisos', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(error_messages={'unique': 'Este correo ya se encuentra registrado.'}, max_length=100, unique=True)),
                ('direction', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=1)),
                ('user_type', models.CharField(blank=True, choices=[('ADM', 'Administrador'), ('CLB', 'Colaborador'), ('ADP', 'Adoptante')], max_length=3)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('idColaborador', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Colaborador',
            },
        ),
        migrations.CreateModel(
            name='Recibe_Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField()),
                ('estado_permiso', models.BooleanField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaborador_to_permiso', to='user.colaborador')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permiso_to_colaborador', to='Permisos.permiso')),
            ],
            options={
                'db_table': 'Recibe_Permiso',
            },
        ),
        migrations.AddField(
            model_name='colaborador',
            name='permisos',
            field=models.ManyToManyField(through='user.Recibe_Permiso', to='Permisos.permiso'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('idAdoptante', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.PositiveIntegerField(blank=True, null=True)),
                ('imagen64', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Adoptante',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idAdministrador', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrador',
                'db_table': 'Administrador',
            },
        ),
    ]
