# Generated by Django 4.2.3 on 2023-08-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptante',
            name='fecha_creacion',
            field=models.DateField(auto_now=True),
        ),
    ]
