# Generated by Django 4.2.6 on 2024-01-28 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('pet', '0001_initial'),
        ('vacuna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacunado',
            name='vacuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunado_to_mascota', to='vacuna.vacuna'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.administrador'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='adoptante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adoptante_mascota', to='user.adoptante'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.animal'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='colaborador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.colaborador'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='vacunas',
            field=models.ManyToManyField(through='pet.Vacunado', to='vacuna.vacuna'),
        ),
    ]
