# Generated by Django 4.2.3 on 2023-08-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_alter_mascota_adopted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='adopted',
            field=models.CharField(choices=[('AD', 'Adoptado'), ('NA', 'No Adoptado')], default='No Adoptado', max_length=2),
        ),
    ]
