# Generated by Django 4.2.3 on 2023-08-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('idActividades', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=700, null=True)),
                ('lugar', models.CharField(blank=True, max_length=300, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actividades',
                'verbose_name_plural': 'Actividades',
                'db_table': 'Actividades',
            },
        ),
    ]
