# Generated by Django 4.2.3 on 2023-08-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_alter_actividades_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='descripcion',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='lugar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
