# Generated by Django 4.2.3 on 2023-08-11 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('actividades', '0004_alter_actividades_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.administrador'),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='colaborador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.colaborador'),
        ),
    ]
