# Generated by Django 4.2.3 on 2023-08-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('idrecompensa', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcionInicial', models.CharField(max_length=200)),
                ('descripcionFinal', models.CharField(max_length=200)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('descuento', models.PositiveIntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/productos')),
                ('activo', models.BooleanField()),
                ('puntos', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
                'db_table': 'recompensa',
            },
        ),
    ]
