# Generated by Django 4.2.6 on 2024-01-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idcurso', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('minutos', models.PositiveIntegerField()),
                ('puntos', models.PositiveIntegerField()),
                ('intentos', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('porcentaje', models.PositiveIntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/cursos')),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Curso_Realizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtained', models.DateField()),
                ('puntos', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Curso_Realizado',
            },
        ),
        migrations.CreateModel(
            name='Formulario_Adoptante',
            fields=[
                ('idFormularioAdoptante', models.AutoField(primary_key=True, serialize=False)),
                ('date_started', models.DateField()),
                ('date_finished', models.DateField(blank=True, null=True)),
                ('calificacion_obtenida', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Formulario_Adoptante',
            },
        ),
        migrations.CreateModel(
            name='Formulario_Curso',
            fields=[
                ('idFormularioCurso', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('calificacion_maxima', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Formulario_Curso',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('idpregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=200)),
                ('puntos', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'pregunta',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('idrespuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=200)),
                ('correcta', models.BooleanField()),
                ('puntos', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'respuesta',
            },
        ),
        migrations.CreateModel(
            name='Respuesta_Seleccionada',
            fields=[
                ('idrespuestaSeleccionada', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje_obtenido', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Respuesta_Seleccionada',
            },
        ),
        migrations.CreateModel(
            name='Tema_Curso',
            fields=[
                ('idtema', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'tema_curso',
            },
        ),
    ]
