# Generated by Django 4.2.3 on 2023-08-15 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('curso', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema_curso',
            name='minutos',
        ),
        migrations.RemoveField(
            model_name='tema_curso',
            name='porcentaje',
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_creacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='idtema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curso.tema_curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='curso_realizado',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='respuesta_seleccionada',
            name='idAdoptante',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='user.adoptante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuesta_seleccionada',
            name='idrespuesta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curso.respuesta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tema_curso',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tema_curso',
            name='fecha_creacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tema_curso',
            name='idAdministrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.administrador'),
        ),
        migrations.AddField(
            model_name='tema_curso',
            name='idColaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.colaborador'),
        ),
        migrations.AddField(
            model_name='tema_curso',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='idAdministrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.administrador'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='idColaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.colaborador'),
        ),
    ]
